In [2]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [7]:
y_true = np.array([2, 1, 2, 2, 0, 1])
y_pred = np.array([2, 1, 1, 1, 1, 1])
cf_mat = confusion_matrix(y_true, y_pred, labels=[1, 2])
print(cf_mat)
cf_mat = confusion_matrix(y_true, y_pred)
print(cf_mat)

[[2 0]
 [2 1]]
[[0 1 0]
 [0 2 0]
 [0 2 1]]


In [10]:
n = cf_mat.shape[0]
for i in range(n):
    TP = cf_mat[i][i]
    FN = cf_mat[i, :i].sum() + cf_mat[i, i+1:].sum()
    FP = cf_mat[:i, i].sum() + cf_mat[i+1:, i].sum()
    TN = cf_mat[:i, :i].sum() + cf_mat[:i, i+1:].sum() + cf_mat[i+1:, :i].sum() + cf_mat[i+1:, i+1:].sum()
    IoU = TP / (TP + FN + FP)
    print('TP:{}, FN:{}, FP:{}, TN:{}, IoU:{}'.format(TP, FN, FP, TN, IoU))

TP:2, FN:0, FP:4, TN:0, IoU:0.3333333333333333
TP:0, FN:1, FP:0, TN:5, IoU:0.0
TP:0, FN:3, FP:0, TN:3, IoU:0.0
