In [2]:
import torch

In [2]:
x = torch.randn(3,4)
y = torch.argmax(x, dim=0)#对应于x中最大元素的索引值
print(x)

tensor([[-0.0157, -1.4397, -0.5338, -0.7564],
        [ 0.7714,  0.4085, -0.1608,  1.1665],
        [ 0.9238, -1.7367,  0.1487,  0.9955]])


In [3]:
print(y)

tensor([2, 1, 2, 1])


In [8]:
x = torch.randn(1, 1)

In [10]:
y = float(x)

In [11]:
x

tensor([[-0.1904]])

In [13]:
type(y)

float

In [10]:
test = [tensor(0., device='cuda:0'), tensor(0.4137, device='cuda:0'), tensor(0.5599, device='cuda:0'), tensor(0.4424, device='cuda:0'), tensor(0.4119, device='cuda:0')]

NameError: name 'tensor' is not defined

In [ ]:
# 